/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ming
 */
public class genapganjilku extends java.awt.Frame {


    /**
     * Creates new form genapganjilku
     */
    public genapganjilku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        panel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        angkaku = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hasil2 = new javax.swing.JTextPane();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        panel.setPreferredSize(new java.awt.Dimension(372, 270));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Process");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel1.setText("Masukkan Angka :");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        angkaku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkakuActionPerformed(evt);
            }
        });
        panel.add(angkaku, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 130, 40));

        jScrollPane1.setViewportView(hasil);

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 290, -1));

        jLabel2.setText("Mengetahui Bilangan Genap atau Ganjil");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 340, 40));

        jScrollPane2.setViewportView(hasil2);

        panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 290, -1));

        add(panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int angka;
        String text;
        
        angka = Integer.parseInt(angkaku.getText() );
        
        if( angka % 2 ==0 ){
            text = "Angka Yang Di Masukkan Bilangan Genap";
        } else {
            text = "Angka Yang Di Masukkan Bilangan Ganjil";
        } hasil.setText(String.valueOf(text));
        
        if( angka <= 1000 ) {
            text = "Berada Di Bawah Range 1000";
        } else {
            text = "Berada Di Atas Range 1000";
        } hasil2.setText(String.valueOf(text));
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void angkakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angkakuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_angkakuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new genapganjilku().setVisible(true);
        
       });
      
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angkaku;
    private javax.swing.JTextPane hasil;
    private javax.swing.JTextPane hasil2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
